Rails/CarrierWave/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'users#index'
  resources :users do
    member do
      post :file
    end
  end 
  resources :files, only: [:edit, :update, :destroy]
  
end

Rails/CarrierWave/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rails/CarrierWave/app/models/file_record.rb
class FileRecord < ApplicationRecord
  belongs_to :user
  mount_uploader :file, FileUploader
end

Rails/CarrierWave/app/models/user.rb
class User < ApplicationRecord
  mount_uploader :image, ImageUploader
  mount_uploader :files, FileUploader
  has_many :file_records, dependent: :destroy
end

Rails/CarrierWave/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Rails/CarrierWave/app/controllers/files_controller.rb
class FilesController < ApplicationController
  def edit
    @file = FileRecord.find_by(id: params[:id])
  end
  
  def update
    @file = FileRecord.find_by(id: params[:id])
    @file.update(params.require(:file_record).permit(:name))
    redirect_to user_path(User.find_by(id: @file.user_id))
  end
  
  def destroy
    @file = FileRecord.find_by(id: params[:id])
    FileUtils.rm("#{Rails.root}/public#{URI.decode(@file.file.to_s)}", :force => true)
    @file.destroy if @file
    redirect_to user_path(User.find_by(id: @file.user_id))
  end
end

Rails/CarrierWave/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, except: [:index, :new, :create]
  
  def index
    @users = User.all
  end
  
  def new
    @user = User.new
  end
  
  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to users_path, notice: "新增成功"
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      redirect_to users_path, notice: "修改成功"
    else
      render :edit
    end
  end
  
  def show
    @file_record = FileRecord.new
  end
  
  def destroy
    @user.destroy if @user
    FileUtils.remove_dir("#{Rails.root}/public/uploads/#{@user.id}-#{@user.name}", :force => true)
    redirect_to users_path
  end

  def file
    @file_record = FileRecord.new(params.require(:file_record).permit(:file, :user_id))
    @file_record.name = params.require(:file_record).permit(:file)['file'].original_filename
    @file_record.save
    render :show
  end

  private
  def find_user
    @user = User.find_by(id: params[:id])
    @file_records = FileRecord.where(user_id: params[:id])
  end

  def user_params
    params.require(:user).permit(:name, :image, :image_cache, :remove_image, :files, :files_cache, :remove_files)
  end
end

Rails/CarrierWave/app/helpers/application_helper.rb
module ApplicationHelper
end

Rails/CarrierWave/app/helpers/files_helper.rb
module FilesHelper
end

Rails/CarrierWave/app/helpers/users_helper.rb
module UsersHelper
end

Rails/CarrierWave/app/views/files/edit.html.erb
<h1>File Edit</h1>
<%= simple_form_for @file, url: file_path do |f| %>
  <%= f.input :name %>
  <%= f.submit %>
<% end %>

Rails/CarrierWave/app/views/users/_form.html.erb
<%= simple_form_for user do |f| %>
  <%= f.input :name, label: "Name " %>
  <br>
　<%= f.input :image, label: "Image " %> <!-- 上傳 -->
  <% if user.image? %>
  　<%= f.check_box :remove_image %> <!-- 刪除 -->
  　<%= image_tag user.image%> <!-- 如果 user 已有圖片的話，就顯示 -->
  <% end %>
  <br>
  <%= f.input :files %>
  <br>
  <%= f.submit %>
<% end %>

Rails/CarrierWave/app/views/users/edit.html.erb
<h1>Edit User</h1>
<hr>
<%= render  "form", user: @user %>
<hr>
<%= link_to  "back", :back %>

Rails/CarrierWave/app/views/users/index.html.erb
<h1>User List</h1>
<hr>
<%= link_to  "new User", new_user_path %>
<table>
  <tr>
    <th></th>
    <th>Name</th>
    <th></th>
  </tr>
  <% @users.each do |user| %>
    <tr>
      <td>
        <%= image_tag user.image if user.image? %>
        <br>
        <%= image_tag user.image_url(:thumb) if user.image? %>
      </td>
      <td><%= link_to  user.name, user_path(user) %></td>
      <td>
          <%= link_to  "edit", edit_user_path(user) %>
          <%= link_to "delete", user_path(user), method: "delete", data:{ confirm: "Are you sure?"} %>
      </td>
    </tr>
  <% end %>
</table>

Rails/CarrierWave/app/views/users/new.html.erb
<h1>Add User</h1>
<hr>
<%= render  "form", user: @user %>
<hr>
<%= link_to  "back", :back %>

Rails/CarrierWave/app/views/users/show.html.erb
<center>
  <%= image_tag @user.image if @user.image? %><br>
  <%= @user.name %><br>
  <% if @user.files? %>
    <%= link_to  @user.files_identifier, @user.files.to_s, download: @user.files_identifier %>
  <% end %>
  <hr>
  <table>
    <tr>
      <th></th>
      <th>Name</th>
      <th></th>
    </tr>
    <% @file_records.each do |file| %>
      <tr>
        <td></td>
        <td><%= link_to  file.name, file.file.to_s %></td>
        <td>
          <%= link_to "下載", file.file.to_s, download: file.file_identifier %>
          <%= link_to "編輯", edit_file_path(file) %>
          <%= link_to "刪除", file_path(file), method: "delete", data:{ confirm: "Are you sure?"} %>
        </td>
      </tr>
    <% end %>
  </table>
  <hr>
  <%= simple_form_for @file_record, url: file_user_path, method: "post" do |f| %>
    <%= f.text_field :user_id, :value => @user.id, readonly: true, hidden: true %>
    <%= f.input :file, label: "檔案上傳：" %><br>
    <%= f.submit %>
  <% end %>
  <%= link_to  "back", "/" %>
</center>