Rails/shopping/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :product_manages, only: [:index, :destroy] do
    resources :product_pictures, only: [:new, :create, :destroy, :update]
  end
  resources :kinds, except: [:show] do
    member do
      get :product
    end
  end
  resources :user_manages, only: [:index, :show]
  resource :user_manage, only: [:update]
  resources :products, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      post :shopping_cart
    end
  end
  resources :shopping_carts, only: [:index, :destroy, :create]
  resources :orders, except: [:new, :create, :edit]

  post "/search", to: "products#search"
  root to: 'common#index'
end

Rails/shopping/app/controllers/common_controller.rb
class CommonController < ApplicationController
  def index
    @details = ProductPicture.where(is_banner: true)
  end
end

Rails/shopping/app/helpers/common_helper.rb
module CommonHelper
end

Rails/shopping/app/views/common/_footer.html.erb
<div>Copyright © 2018 IffyArt Inc. All rights reserved</div>

Rails/shopping/app/views/common/_manage_list.html.erb
<div class="list-group">
    <a class="list-group-item active">
        管理類別
    </a>
    <%= link_to  "產品管理", product_manages_path ,class:'list-group-item'%>
    <%= link_to  "訂單管理", orders_path ,class:'list-group-item'%>
</div>

Rails/shopping/app/views/common/_navbar.html.erb
<nav class="navbar navbar-fixed-top">
    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/">Little JJ</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to "產品列表<br>Items".html_safe, products_path %>
                </li>
                <% if !current_user %>
                  <li> <%= link_to("會員登入<br>Sign in".html_safe, new_user_session_path) %> </li>
                <% else %>
                  <li> <%= link_to  "會員管理<br>Member".html_safe, user_manage_path(current_user) %></li>
                  <li>
                    <% if current_user and current_user.is_admin %>
                      <%= link_to "後台管理<br>Management".html_safe, user_manages_path %>
                    <% else %>
                      <%= link_to  "訂單管理<br>Order".html_safe, orders_path %>
                    <% end %>
                  </li>
                  <li> <%= link_to("會員登出<br>Sign Out".html_safe, destroy_user_session_path, method: :delete) %> </li>
                <% end %>
                <li>
                    <a href="/shopping_carts" class="btn cart">
                        <% if current_user and current_user.shopping_carts.size != 0 %>
                          <div class="cartNumber"><%= current_user.shopping_carts.size %></div>
                        <% end %>
                        <i class="fa fa-shopping-cart" aria-hidden="true"></i>
                    </a>
                </li>

                <li>
                    <a class="btn serch" data-toggle="collapse" href="#nav-collapse" aria-expanded="false" aria-controls="nav-collapse3">
                        <i class="fa fa-search" aria-hidden="true"></i>
                    </a>
                </li>
            </ul>
            <div class="collapse nav navbar-nav nav-collapse slide-down" id="nav-collapse">
                <%= form_for product_search, html: {class: 'navbar-form navbar-right'}, url: search_path do |f| %>
                    <div class="form-group">
                        <%= f.text_field :name, class: 'form-control', placeholder: 'Search' %>
                    </div>
                    <%= button_tag(type: 'submit', class: "btn btn-danger") do %>
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</nav>

Rails/shopping/app/views/common/_product_kind.html.erb
<a class="list-group-item active">
  產品類別
</a>
<% kinds.each do |kind| %>
  <%= link_to (kind.id == 1)? "全部" : kind.name, product_kind_path(kind),class: "list-group-item" %>
<% end %>

Rails/shopping/app/views/common/index.html.erb
<section class="row">
        <div class="col-xs-12  col-md-12 text-center">
            <div id="myCarousel" class="carousel slide" data-ride="carousel">
                <!-- Indicators -->
                <ol class="carousel-indicators">
                    <li data-target="#myCarousel" data-slide-to="0" class=""></li>
                    <li data-target="#myCarousel" data-slide-to="1" class=""></li>
                    <li data-target="#myCarousel" data-slide-to="2" class="active"></li>
                </ol>
                <div class="carousel-inner" role="listbox">
                    <div class="item">
                        <img class="first-slide" src="assets/banner1.jpg" alt="First slide">
                        <div class="container">
                            <div class="carousel-caption">
                                <p></p>
                            </div>
                        </div>
                    </div>
                    <div class="item">
                        <img class="second-slide" src="assets/banner1.jpg" alt="Second slide">
                        <div class="container">
                            <div class="carousel-caption">
                                <p></p>
                            </div>
                        </div>
                    </div>
                    <div class="item active">
                        <img class="third-slide" src="assets/banner1.jpg" alt="Third slide">
                        <div class="container">
                            <div class="carousel-caption">
                                <p></p>
                            </div>
                        </div>
                    </div>
                </div>
                <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>
            </div>
        </div>
    </section>
    <section class="row">
        <div class="col-xs-12  col-md-8">
            <div class="">
                <h1>Hello, world!</h1>
                <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured
                    content or information.</p>
                <p>
                    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                </p>
            </div>
        </div>
        <div class="col-xs-12  col-md-4 text-center">
            <div class="list-group">
                <a href="#" class="list-group-item active">
                    Cras justo odio
                </a>
                <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
                <a href="#" class="list-group-item">Morbi leo risus</a>
                <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                <a href="#" class="list-group-item">Vestibulum at eros</a>
            </div>
        </div>
    </section>
    <section class="row">
        <div class="col-xs-12  col-md-4 text-center">
            <div class="list-group">
                <a href="#" class="list-group-item active">
                    Cras justo odio
                </a>
                <a href="#" class="list-group-item">Dapibus ac facilisis in</a>
                <a href="#" class="list-group-item">Morbi leo risus</a>
                <a href="#" class="list-group-item">Porta ac consectetur ac</a>
                <a href="#" class="list-group-item">Vestibulum at eros</a>
            </div>
        </div>
        <div class="col-xs-12  col-md-8">
            <div class="">
                <h1>Hello, world!</h1>
                <p>This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured
                    content or information.</p>
                <p>
                    <a class="btn btn-primary btn-lg" href="#" role="button">Learn more</a>
                </p>
            </div>
        </div>
    </section>