Rails/shopping/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :product_manages, only: [:index, :destroy] do
    resources :product_pictures, only: [:new, :create, :destroy, :update]
  end
  resources :kinds, except: [:show] do
    member do
      get :product
    end
  end
  resources :user_manages, only: [:index, :show]
  resource :user_manage, only: [:update]
  resources :products, only: [:index, :show, :edit, :update, :new, :create] do
    member do
      post :shopping_cart
    end
  end
  resources :shopping_carts, only: [:index, :destroy, :create]
  resources :orders, except: [:new, :create, :edit]

  post "/search", to: "products#search"
  root to: 'common#index'
end

Rails/shopping/app/models/shopping_cart.rb
class ShoppingCart < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

Rails/shopping/app/controllers/shopping_carts_controller.rb
class ShoppingCartsController < ApplicationController
  before_action :authenticate_user!

  def index
  end

  def create
    order = current_user.orders.create
    current_user.shopping_carts.map{|val| OrderDetail.create(order_id: order.id, product_id: val.product.id, amount: val.amount, price: val.product.price)}
    current_user.shopping_carts.destroy_all
    redirect_to shopping_carts_path, notice: "訂單成立"
  end

  def destroy
    shopping_cart = current_user.shopping_carts.find_by(id: params[:id])
    shopping_cart.product.update(amount: shopping_cart.product.amount + shopping_cart.amount)
    current_user.shopping_carts.find_by(id: params[:id]).destroy
    redirect_to shopping_carts_path
  end
end

Rails/shopping/app/helpers/shopping_carts_helper.rb
module ShoppingCartsHelper
end

Rails/shopping/app/views/shopping_carts/index.html.erb
<h1>ShoppingCart List</h1>
<table class="table table-hover">
  <tr>
    <th>Product</th>
    <th>Price</th>
    <th>Amount</th>
    <th>Total</th>
    <th></th>
  </tr>
  <% current_user.shopping_carts.each do |cart| %>
  <tr>
    <td><%= link_to  cart.product.name, product_path(cart.product), data: { turbolinks: false } %></td>
    <td><%= cart.product.price %></td>
    <td>
      <%= form_for cart, url: shopping_cart_product_path(id: cart.product.id), method: "post" do |f| %>
        <%= link_to  "-", shopping_cart_product_path(id: cart.product.id, shopping_cart: {amount: -1}), method: "post", class: "btn btn-default" %>
        <%= f.text_field :amount, readonly: true %>
        <%= link_to  "+", shopping_cart_product_path(id: cart.product.id, shopping_cart: {amount: 1}), method: "post", class: "btn btn-default" %>
      <% end %>
    </td>
    <td><%= cart.product.price * cart.amount %></td>
    <td>
      <%= link_to "刪除", shopping_cart_path(cart), method: "delete", data:{ confirm: "Are you sure?"} %>
    </td>
  </tr>
  <% end %>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td>總計： <%= current_user.shopping_carts.map{|val| val.product.price * val.amount }.sum %></td>
    <td></td>
  </tr>
</table>
<% if current_user.shopping_carts.size != 0 %>
  <%= link_to  "生成訂單", shopping_carts_path, method: "post", class: "btn btn-success" %>
<% end %>